ASLTS: modularize compile, disassemble and binary comparison
This is done by creating new rules and performing recursive calls to make to invoke them.

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -30,6 +30,7 @@ COMMON_ASL_FLAGS= "-of -cr -vs -l -sc -sa -ic -ta -ts -so -lm -ln -ls -li"
 COMPILER_LOG="$(TOP)/tmp/aml/$(aslversion)/compile.txt"
 COMPILER_ERROR_LOG="$(TOP)/tmp/aml/$(aslversion)/error.txt"
 
+
 # Create general directory
 
 GDMODE=775
@@ -46,7 +47,6 @@ empty_all:	FORCE
 
 ${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%}:
 	@$(INST.dir)
-
 
 # Make-install one particular Test Case for all modes
 
@@ -72,83 +72,29 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 			for j in ${ASLMOD} $(ASLMODADD); do \
 				echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
 				>&2 printf "%-18s" "    Type: $$CUR_AMLDIR "; \
-				>&2 printf  "Compile"; \
-				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-				ret=$$?; \
-				echo "" >> $(COMPILER_LOG); \
-				if [ $(OPT) -eq 0 ]; then \
+				>&2 printf "\n    "; \
+                                make compile_testcase MSG="with normal test suite flags" EXTRAFLAGS="$$j.asl" FNAME="$$j"; \
+				if [ $(OPT)$$CUR_AMLDIR = "0nopt/32" ] || [ $(OPT)$$CUR_AMLDIR = "0nopt/64" ]; then \
 					for k in ${AMLMOD}; do \
-						>&2 printf " => Disassemble"; \
-						echo "---- Diasassemble: $$k.aml" >> $(COMPILER_LOG); \
-						echo "---- Diasassemble: $$k.aml" >> $(COMPILER_ERROR_LOG); \
-						"$(ASL)" -p $$k-aslminus -cr -vs $$CUR_ASLFLAGS $(ADD_ASLFLAGS) -od -dl $$k.aml >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-						if [ ! -f $$k-aslminus.dsl ]; then \
-							>&2 printf " [[ Error: disassembly failed of $$k.aml failed ]]\n"; \
-							>&2 printf "          Flags used: -p $$k-aslminus -cr -vs $$CUR_ASLFLAGS $(ADD_ASLFLAGS) -od -dl\n\n"; \
-							exit 1; \
-						fi; \
-						>&2 printf " => Recompile"; \
-						echo "---- Recompile: $$k.dsl" >> $(COMPILER_LOG); \
-						echo "---- Recompile: $$k.dsl" >> $(COMPILER_ERROR_LOG); \
-						"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$k-aslminus.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-						if [ ! -f $$k-aslminus.aml ]; then \
-							>&2 printf " [[ Error: re-compilation of $$k-aslminus.dsl failed]]\n"; \
-							>&2 printf "          Flags used: $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS)\n\n"; \
-							exit 1; \
-						fi; \
-						rm $$k-aslminus.asm; \
-						rm $$k-aslminus.c; \
-						rm $$k-aslminus.h; \
-						rm $$k-aslminus.i; \
-						rm $$k-aslminus.hex; \
-						rm $$k-aslminus.map; \
-						rm $$k-aslminus.nsp; \
-						rm $$k-aslminus.offset.h; \
-						rm $$k-aslminus.src; \
-						if [ $$CUR_AMLDIR = "nopt/32" ] || [ $$CUR_AMLDIR = "nopt/64" ]; then \
-							>&2 printf " => Binary compare"; \
-							acpibin -c $$k.aml $$k-aslminus.aml >> comparison_output.txt; \
-							if [ $$? != 0 ]; then \
-								>&2 printf " [[ Error: comparison of $$k.aml and $$k-aslminus.aml do not match ]]"; \
-								cat comparison_output.txt | sed '1,/^Error/d' | sed 's/Error - Byte mismatch at offset     /         => /g' | sed -n 1,10p > comparison_output.txt;\
-								>&2 printf "\n"; \
-								cat comparison_output.txt >&2 ; \
-								>&2 printf "        "; \
-								#exit 1; \
-							else \
-								>&2 printf " => Removing files"; \
-								rm $$k-aslminus.lst; \
-								rm $$k-aslminus.aml; \
-								rm $$k-aslminus.dsl; \
-							fi; \
-						fi; \
-						>&2 printf " => Done"; \
+						>&2 printf "\n    "; \
+						a=`make compile_testcase MSG="with externals in place" EXTRAFLAGS="-p $$k-ext $$j.asl" FNAME="$$k-ext"`; \
+						>&2 printf "\n        "; \
+						>&2 printf "aaaaaa = $a\n"; \
+						make disassemble_testcase MSG="ASL-" EXTRAFLAGS="-p $$k-aslminus $$k-ext.aml" LEGACY="yes"; \
+						make compile_testcase MSG="ASL- (recompile)" EXTRAFLAGS="$$k-aslminus.dsl" FNAME="$$k-aslminus"; \
+						make binary_compare MSG="ASL-" BASE="$$k" TEST="$$k-aslminus"; \
+						>&2 printf "\n        "; \
+						make disassemble_testcase MSG="ASL+" EXTRAFLAGS="-p $$k-aslplus $$k-ext.aml" LEGACY="no"; \
+						make compile_testcase MSG="ASL+ (recompile)" EXTRAFLAGS="$$k-aslplus.dsl" FNAME="$$k-aslplus"; \
+						make binary_compare MSG="ASL+" BASE="$$k" TEST="$$k-aslplus"; \
 					done; \
-				fi; \
-				>&2 printf " => Removing files"; \
-				rm $$j.asm; \
-				rm $$j.c; \
-				rm $$j.h; \
-				rm $$j.i; \
-				rm $$j.hex; \
-				rm $$j.lst; \
-				rm $$j.map; \
-				rm $$j.nsp; \
-				rm $$j.offset.h; \
-				rm $$j.src; \
-				>&2 printf " => Done"; \
-				if [ $$ret != 0 ]; then \
-					rval=1; \
-					>&2 echo "**** Unexpected iASL failure in $$dd/$$j.asl!"; \
-					exit 1; \
 				fi; \
 			done; \
 			>&2 echo ""; \
-			if [ $$ret != 0 ]; then break; fi; \
 			for j in ${AMLMOD}; do \
 				ls -l $$j.aml >> $(COMPILER_LOG); \
 				echo "---- Move: $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR" >> $(COMPILER_LOG); \
-				mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
+				#mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
 				ret=$$?; \
 				if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!" >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); break; fi; \
 			done; \
@@ -158,6 +104,45 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 		rval=1; \
 	fi; \
 	if [ $$rval != 0 ]; then exit 1; fi
+
+# Compilation helpers
+compile_testcase:
+	>&2 printf " => Compile $(MSG)"; \
+	"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $(EXTRAFLAGS) >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+	compileRet=$$?; \
+	rm $(FNAME).asm $(FNAME).c  $(FNAME).h $(FNAME).i $(FNAME).hex $(FNAME).lst $(FNAME).map $(FNAME).nsp $(FNAME).offset.h $(FNAME).src; \
+	if [ $$compileRet -ne 0 ]; then \
+		rval=1; \
+		>&2 echo "[[ Unexpected compilation failure in $(FNAME).asl! ]]"; \
+	fi;
+	echo "$$compileRet"
+
+
+disassemble_testcase:
+	>&2 printf " => Disassemble to $(MSG)"; \
+	if [ "$(LEGACY)" = "yes" ]; then\
+		DISASM_FLAG="-dl";\
+	else \
+		DISASM_FLAG="-d";\
+	fi; \
+	"$(ASL)" -od -cr -vs $$CUR_ASLFLAGS $(ADD_ASLFLAGS)  $(DISASM_FLAG) $(EXTRAFLAGS) >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+	disasmRet=$$?; \
+	if [ $$disasmRet -ne 0 ]; then \
+		rval=1; \
+		>&2 echo "[[ Binary comparison between $(BASE).aml and $(TEST).aml does not match! ]]"; \
+	fi; \
+
+
+binary_compare:
+	>&2 printf " => Binary compare $(MSG)"; \
+        acpibin -c $(BASE).aml $(TEST).aml; \
+	binCompRet=$$?; \
+	if [ $$binCompRet -ne 0 ]; then \
+		rval=1; \
+		>&2 printf "\n        "; \
+		>&2 echo "[[ Binary comparison between $(BASE).aml and $(TEST).aml does not match! ]]"; \
+	fi; \
+
 
 # Make-install one particular Test Case for all modes.
 # Move results to aslts/tmp/aml directory.
