ASLTS: add converter test sequence
The converter test sequence is as follows:
1.) convert the test case
2.) compile the resulting .dsl from step 1
3.) perform a binary comparison from .aml files generated from the original compile and step 2

Note: due to the nature of the converter, this will leave additional .dsl files

Signed-off-by: Erik Schmauss <erik.schmauss@intel.com>

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -118,6 +118,30 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 								>&2 printf " => Success!"; \
 								rm comparison_output.txt; \
 							fi; \
+							>&2 printf " => Convert"; \
+							"$(ASL)" $$CUR_ASLFLAGS "$(CORE_ASL_FLAGS)" $(ADD_ASLFLAGS) -ca $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+							if [ $$? != 0 ]; then \
+								>&2 printf " [[ Error while converting ]] "; \
+							fi; \
+							>&2 printf " => Recompile converted AML"; \
+							"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+							if [ $$? != 0 ]; then \
+								>&2 printf " [[ Error while recompiling ]] "; \
+							fi; \
+							>&2 printf " => Binary compare"; \
+							rm -f comparison_output.txt; \
+							acpibin -c $$k.aml $$j.aml >> comparison_output.txt; \
+							if [ $$? != 0 ]; then \
+								>&2 printf " [[ Error: comparison of $$k.aml and $$j.aml do not match ]]"; \
+								cat comparison_output.txt | sed '1,/^Error/d' | sed 's/Error - Byte mismatch at offset     /         => /g' | sed -n 1,10p > comparison_output.txt;\
+								>&2 printf "\n"; \
+								cat comparison_output.txt >&2 ; \
+								>&2 printf "        "; \
+								#exit 1; \
+							else \
+								>&2 printf " => Success!"; \
+								rm comparison_output.txt; \
+							fi; \
 						fi; \
 						if [ ! -f comparison_output.txt ]; then \
 							>&2 printf " => Removing files"; \
